# Расположение логов тех журнала 1С
path: "D:\\temp\\1C_log"
# Удалять табуляции в контекстных строках
delete_tabs_in_contexts: true
# Заменять постфиксы виртуальных таблиц в контекстах, например #tt36 на #tt
# Может использоваться для группировки контекстов
delete_postfix_in_name_virtual_tables: true
#
#

# Типы событий тех журнала, которые могут содержать длинные строки '...' и переносы строк \n
tech_log_details_events: "Context|Txt|Descr|DeadlockConnectionIntersections|ManagerList|ServerList|Sql|Sdbl|E ds|URI|Headers"
#
# Путь, где будут распологаться логи программы
path_logfile: "D:\\Temp\\fucklogs\\"
#
# Глубина фиксации ошибок при работе программы:
#   1 - только ошибки
#   2 - ошибки и предупреждения
#   3 - ошибки, предупреждения и информация
log_level: 3
#
# Срок жизни файлов логов в днях
log_life_span: 4
#
# Уровень параллелизма
maxdop: 5
#
# 0 - отключена сортировка файлов по размеру, 1 - сортировка по убыванию, 2 - сортировка по возрастанию
# полезно включать при массовых операциях, для равномерного распределения файлов по потокам
sorting: 1
